/* Generated by tools/generate-localization.cjs; static UTF-16, no translation runtime. */
static int uiLanguage=0;
static const WCHAR *languageNames[]={L"English",L"한국어",L"日本語",L"简体中文",L"Español"};
#define TXT_idle 0
#define TXT_working 1
#define TXT_done 2
#define TXT_question 3
#define TXT_error 4
#define TXT_stopped 5
#define TXT_unknown 6
#define TXT_app 7
#define TXT_quota 8
#define TXT_previewSuffix 9
#define TXT_longSuffix 10
#define TXT_tooltip 11
#define TXT_status 12
#define TXT_auto 13
#define TXT_ack 14
#define TXT_preview 15
#define TXT_quotaPreview 16
#define TXT_longPreview 17
#define TXT_unreadPreview 18
#define TXT_ackQuota 19
#define TXT_badgeMenu 20
#define TXT_animate 21
#define TXT_changeIcon 22
#define TXT_browserSettings 23
#define TXT_hide 24
#define TXT_exit 25
#define TXT_charcoal 26
#define TXT_red 27
#define TXT_blue 28
#define TXT_green 29
#define TXT_purple 30
#define TXT_white 31
#define TXT_language 32
#define TXT_saveFailed 33
#define TXT_sessions 34
#define TXT_settings 35
#define TXT_noSessions 36
#define TXT_loadingTitle 37
#define TXT_readFailed 38
#define TXT_scroll 39
#define TXT_sessionWindow 40
#define TXT_projectWindow 41
#define TXT_launchLinkFailed 42
#define TXT_openLinkFailed 43
#define TXT_browserFailed 44
#define TXT_launchBrowserFailed 45
static const WCHAR *uiText[][5]={
{L"Idle",L"대기중",L"待機中",L"空闲",L"En espera"},
{L"Working",L"작업중",L"作業中",L"工作中",L"Trabajando"},
{L"Completed",L"작업완료",L"完了",L"已完成",L"Completado"},
{L"Question",L"질문있음",L"質問あり",L"有问题",L"Pregunta"},
{L"Error",L"오류",L"エラー",L"错误",L"Error"},
{L"Stopped",L"중지",L"停止",L"已停止",L"Detenido"},
{L"Detection uncertain",L"감지확인 필요",L"検出の確認が必要",L"检测待确认",L"Detección incierta"},
{L"Codex Tray Pet",L"Codex 펫",L"Codex トレイペット",L"Codex 托盘宠物",L"Codex Tray Pet"},
{L"Usage limit reached",L"사용량 제한으로 중지",L"使用量制限で停止",L"已达用量限制",L"Límite de uso alcanzado"},
{L" · Preview",L" · 미리보기",L" · プレビュー",L" · 预览",L" · Vista previa"},
{L" · Task over 10 min",L" · 10분 이상 작업 있음",L" · 10分以上の作業",L" · 有任务超过10分钟",L" · Tarea de más de 10 min"},
{L"Codex Pet · %ls%ls · Unread %d%ls",L"Codex 펫 · %ls%ls · 미확인 완료 %d개%ls",L"Codex ペット · %ls%ls · 未読 %d%ls",L"Codex 宠物 · %ls%ls · 未读 %d%ls",L"Codex Pet · %ls%ls · Sin leer %d%ls"},
{L"Status: %ls",L"상태: %ls",L"状態: %ls",L"状态：%ls",L"Estado: %ls"},
{L"Automatic detection",L"자동 감지",L"自動検出",L"自动检测",L"Detección automática"},
{L"Acknowledge completed / error / stopped",L"완료·오류·중지 확인",L"完了・エラー・停止を確認",L"确认完成、错误和停止",L"Confirmar completado / error / detenido"},
{L"State preview",L"상태 미리보기",L"状態プレビュー",L"状态预览",L"Vista previa del estado"},
{L"Usage-limit alert",L"사용량 제한 경고",L"使用量制限の警告",L"用量限制警告",L"Aviso de límite de uso"},
{L"Task over 10 minutes",L"10분 이상 작업",L"10分以上の作業",L"超过10分钟的任务",L"Tarea de más de 10 minutos"},
{L"Unread-result counter",L"미확인 완료 숫자",L"未読結果の件数",L"未读结果数量",L"Contador de resultados sin leer"},
{L"Acknowledge usage-limit alert",L"사용량 제한 알림 확인",L"使用量制限の通知を確認",L"确认用量限制提示",L"Confirmar aviso de límite de uso"},
{L"Counter color",L"숫자 배지 색상",L"件数バッジの色",L"数量徽标颜色",L"Color del contador"},
{L"Animation and color changes",L"움직임·색 변화",L"動き・色の変化",L"动画与颜色变化",L"Animación y cambios de color"},
{L"Change icon...",L"아이콘 변경...",L"アイコンを変更...",L"更换图标...",L"Cambiar icono..."},
{L"Open settings in browser...",L"브라우저에서 설정 열기...",L"ブラウザーで設定を開く...",L"在浏览器中打开设置...",L"Abrir ajustes en el navegador..."},
{L"Hide pet for this Codex run",L"이번 코덱스 실행 동안 펫 숨기기",L"今回のCodex起動中は非表示",L"本次Codex运行期间隐藏宠物",L"Ocultar durante esta ejecución de Codex"},
{L"Stop watcher",L"감시 프로그램 종료",L"監視プログラムを終了",L"退出监视程序",L"Detener monitor"},
{L"Charcoal",L"차콜",L"チャコール",L"炭灰",L"Carbón"},
{L"Red · default",L"빨강 · 기본값",L"赤・初期値",L"红色 · 默认",L"Rojo · predeterminado"},
{L"Blue",L"파랑",L"青",L"蓝色",L"Azul"},
{L"Green",L"초록",L"緑",L"绿色",L"Verde"},
{L"Purple",L"보라",L"紫",L"紫色",L"Morado"},
{L"White",L"흰색",L"白",L"白色",L"Blanco"},
{L"Language",L"언어",L"言語",L"语言",L"Idioma"},
{L"Could not save settings.",L"설정을 저장하지 못했습니다.",L"設定を保存できませんでした。",L"无法保存设置。",L"No se pudieron guardar los ajustes."},
{L"Sessions",L"세션",L"セッション",L"会话",L"Sesiones"},
{L"Settings",L"설정",L"設定",L"设置",L"Ajustes"},
{L"No sessions to display.",L"표시할 세션이 없습니다.",L"表示するセッションはありません。",L"没有可显示的会话。",L"No hay sesiones para mostrar."},
{L"Loading title",L"제목 확인 중",L"タイトルを確認中",L"正在读取标题",L"Cargando título"},
{L"Could not sync read state.",L"읽음 상태를 동기화할 수 없습니다.",L"既読状態を同期できません。",L"无法同步已读状态。",L"No se pudo sincronizar el estado de lectura."},
{L"%d–%d / %d · Scroll to see more",L"%d–%d / %d · 휠로 보기",L"%d–%d / %d · スクロールで表示",L"%d–%d / %d · 滚动查看",L"%d–%d / %d · Desplázate para ver más"},
{L"Codex sessions",L"코덱스 세션",L"Codex セッション",L"Codex 会话",L"Sesiones de Codex"},
{L"Codex project",L"코덱스 프로젝트",L"Codex プロジェクト",L"Codex 项目",L"Proyecto de Codex"},
{L"Could not launch the Codex session link.",L"Codex 세션 링크를 실행할 수 없습니다.",L"Codexのセッションリンクを実行できません。",L"无法启动Codex会话链接。",L"No se pudo abrir el enlace de la sesión de Codex."},
{L"Could not open the session. Check Codex's URL association.",L"Codex 세션 링크를 열 수 없습니다. Codex 앱의 URL 연결을 확인해 주세요.",L"セッションを開けません。CodexのURL関連付けを確認してください。",L"无法打开会话。请检查Codex的URL关联。",L"No se pudo abrir la sesión. Comprueba la asociación de URL de Codex."},
{L"Could not open browser settings.",L"브라우저 설정을 열지 못했습니다.",L"ブラウザー設定を開けませんでした。",L"无法打开浏览器设置。",L"No se pudieron abrir los ajustes del navegador."},
{L"Could not start the browser.",L"브라우저를 실행하지 못했습니다.",L"ブラウザーを起動できませんでした。",L"无法启动浏览器。",L"No se pudo iniciar el navegador."}
};
static const WCHAR *tr(int key){return uiText[key][uiLanguage>=0&&uiLanguage<5?uiLanguage:0];}
static const WCHAR *stateName(int state){return tr(state>=0&&state<7?state:TXT_unknown);}
